model_configs:
  vitb:
    encoder: vitb
    features: 128
    out_channels:
    - 96
    - 192
    - 384
    - 768
  vitg:
    encoder: vitg
    features: 384
    out_channels:
    - 1536
    - 1536
    - 1536
    - 1536
  vitl:
    encoder: vitl
    features: 256
    out_channels:
    - 256
    - 512
    - 1024
    - 1024
  vits:
    encoder: vits
    features: 64
    out_channels:
    - 48
    - 96
    - 192
    - 384
parser:
  bs: 4
  encoder: vitb
  epochs: 40
  img_size: 518
  local_rank: 0
  lr: 5.0e-06
  max_depth: 20
  min_depth: 0.001
  port: null
  pretrained_from: ../../autodl-tmp/deepth_model/depth_anything_v2_vitb.pth
  save_path: ../../autodl-tmp/result_deepth
